---
- name: build war
  hosts: build
  become: yes

  tasks:
    - name: apt-update
      apt:
        update_cache: yes

    - name: install git
      apt:
        name: git
        state: present

    - name: install openjdk-11-jdk
      apt:
        name: openjdk-11-jdk
        state: present

    - name: install maven
      apt:
        name: maven
        state: present

    - name: git clone
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
        dest: /home/regina/homework3/
        clone: yes

    - name: create war file
      shell: chdir=/home/regina/homework3  mvn package

    - name: Set war file Rights
      file:
        path: "/home/regina/homework3/target/hello-1.0.war"
        owner: root
        group: root
        mode: 0777   


    - name: copy war to remote host
      copy:
        src: /home/regina/homework3/target/hello-1.0.war
        dest: "root@51.250.92.43:/tmp"
        remote_src: yes
         

- name: prod
  hosts: prod
  become: yes

  tasks:
    - name: apt-update
      apt:
        update_cache: yes
      
    - name: install tomcat
      apt:
        name: tomcat9
        state: present